### PR TITLE
WIP: DO NOT MERGE! Downstream bugfix

### PR DESCRIPTION
**Pull request by inoxx03**
Backported a small markup bugfix that resolves downstream build issues.
@rhoads-zach @tradej Please feel free to merge if this look OK to you. Thank you.

### CODE REVIEW

**Comment by tradej** [comment]
@inoxx03 I fail to see why you made the changes in e4ab71d0718f4bfe1cb01e040b0bd49ede2650ef. Care to elaborate, please?

**Comment by tradej** [comment]
Try removing all `:context!:` statements, they shouldn't be used at all IMO. With it, also get rid of the context setting on line 188, the previous setting should be in effect.

**Comment by inoxx03** [comment]
@tradej Sure, can do that. However, I'll need to do it in downstream first and sync this PR with the change.

**Comment by inoxx03** [comment]
This fix has already been applied as part of the last downstream sync. This PR contains no useful changes and can be closed. Closing.

**Pull request closed without merging**
