### PR TITLE
Updated JWT auth handler config description. Fixes https://issues.jbo…

### PR DESCRIPTION
**Pull request by spisiakm**
…ss.org/browse/RHOARDOC-1285

### CODE REVIEW

**Comment by Ladicek** [comment]
@spisiakm I don't know what the problem is, but this PR fails validation :-)

@rhoads-zach could you maybe clarify? Thanks!

**Comment by rhoads-zach** [comment]
[test]

**Comment by rhoads-zach** [comment]
@Ladicek @spisiakm tests pass.

Merging.

**Comment by Ladicek** [comment]
Thanks @rhoads-zach!

**Comment by spisiakm** [comment]
Thanks all!

**Pull request merged**
