### PR TITLE
RHOARDOC-1539: Updated SB app code example

### PR DESCRIPTION
**Pull request by tradej**
Resolves [RHOARDOC-1539](https://issues.jboss.org/browse/RHOARDOC-1539).

HTML preview:

* SB 2.1: https://url.corp.redhat.com/39a1aaf
* SB 1.5: https://url.corp.redhat.com/32d67a2

### CODE REVIEW

**Comment by liborfuka** [comment]
Code does not want to compile. Compilation errors:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project my-app: Compilation failure: Compilation failure: 
[ERROR] /home/lfuka/Git/test-doc-sb/src/main/java/com/example/Controller.java:[3,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /home/lfuka/Git/test-doc-sb/src/main/java/com/example/Controller.java:[4,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /home/lfuka/Git/test-doc-sb/src/main/java/com/example/Controller.java:[5,47] package org.springframework.web.bind.annotation does not exist
[ERROR] /home/lfuka/Git/test-doc-sb/src/main/java/com/example/Controller.java:[7,2] cannot find symbol
[ERROR]   symbol: class RestController
[ERROR] /home/lfuka/Git/test-doc-sb/src/main/java/com/example/Controller.java:[10,6] cannot find symbol
[ERROR]   symbol:   class GetMapping
[ERROR]   location: class com.example.Controller

**Comment by geoand** [comment]
@liborfuka do you have a zip of project you are using?

**Comment by liborfuka** [comment]
[test-doc-sb.zip](https://github.com/fabric8-launcher/launcher-documentation/files/2936042/test-doc-sb.zip)

**Comment by geoand** [comment]
@liborfuka You need to include:

```
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
```

in the pom.xml in order to use Spring MVC

**Comment by liborfuka** [comment]
@tradej you have a bug in pom.xml in text.

**Comment by liborfuka** [comment]
@geoand I found another problem:
curl http://localhost:8080 does not show {"content":"Greetings!"}

**Comment by geoand** [comment]
@liborfuka it worked just fine for me.

**Comment by geoand** [comment]
Note that the dependencies section I used in `pom.xml` is:

```
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
  </dependencies>
```

**Comment by liborfuka** [comment]
curl http://localhost:8080 shows nothing for me.

**Comment by geoand** [comment]
Do you try the dependencies I have shows?

**Comment by liborfuka** [comment]
Yes I do.

**Comment by geoand** [comment]
Can you send your updated zip file please?

**Comment by liborfuka** [comment]
[test-doc-sb-v2.zip](https://github.com/fabric8-launcher/launcher-documentation/files/2936161/test-doc-sb-v2.zip)

**Comment by geoand** [comment]
@liborfuka please remove all the stuff you have in your `dependencies` and use only the ones I added above.
You basically shouldn't have `spring-boot-starter-web` and `resteasy-spring-boot-starter` together

**Comment by liborfuka** [comment]
Thanks @geoand.
@tradej you need to update <dependencies> section. Let me know when it is updated and i will retest it all again.

**Comment by geoand** [comment]
Your are welcome @liborfuka !

**Comment by inoxx03** [comment]
@geoand thank you for providing the code and required dependencies, @tradej thank you for the doc updates.
@liborfuka I've updated the POM example to only contain the 3 starters specified by @geaoand.
The procedure seems to work as expected now:
* `mvn clean package` compiles successfully.
* `mvn spring-boot:run` works
* `curl http://localhost:8080` shows ` {"content":"Greetings!"}`
Please confirm whether it also works for you. Thank you.

**Comment by liborfuka** [comment]
LGTM

**Comment by inoxx03** [comment]
thank you @liborfuka :)

**Comment by tradej** [comment]
[test]

**Pull request merged**
