### PR TITLE
Fixes  Issue-1143 Add live application debugging - Spring Boot

### PR DESCRIPTION
**Pull request by lavernw1**
Initial WIP PR to Include common files for runtime application debug

### CODE REVIEW

**Comment by rhoads-zach** [comment]
found the issue, will fix in separate PR.

**Comment by rhoads-zach** [comment]
@lavernw1 i have fixed the build issue in a separate PR and merged, but there is also a merge conflict. Please rebase your branch and fix the merge conflict.

Once thats done, i'll merge.

**Comment by tradej** [comment]
Please consider not merging this in favour of #1005. Thank you.

**Comment by lavernw1** [comment]
@rhoads-zach @tradej @inoxx03 -  This content wont be merged. Spring Boot content has been included   in #1005

**Comment by inoxx03** [comment]
Thank you @lavernw1. If we don't intend to merge this content, then I'll close this PR.

**Pull request closed without merging**
