### PR TITLE
changes base url. fixes RHOARDOC-1118

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@Ladicek 

All of these files one of the following, and require a hard-coded reference:
* readme file
* property file used by readme
* file used directly by the front end (for now)

**Comment by Ladicek** [comment]
I know that some of the files are READMEs or properties, but I thought some of them are not. Sorry if I was wrong :-)

**Comment by tradej** [comment]
I understand the README file and the property files, but I thought the Launcher did include `document-attributes.adoc`. Anyway, if that's not the case, the change looks good.

Two things:

* I was not able to check the liveness because the files are not up yet.
* I am getting an SSL bad certificate domain error when I access any of the guide URLs. I presume it will go away when the files are up, but I wouldn't like for it to fall through the cracks if it doesn't.

**Comment by rhoads-zach** [comment]
amended PR with latest changes.

New base url: https://launcher.fabric8.io

@gastaldi @tradej @inoxx03 @Ladicek let me know what you think

**Comment by tradej** [comment]
LGTM.

**Pull request merged**
