### PR TITLE
updated redirect rules. Fixes RHOARDOC-1224

### PR DESCRIPTION
**Pull request by rhoads-zach**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
@gastaldi @tradej @inoxx03 mind taking a look at this?

**Comment by gastaldi** [comment]
@rhoads-zach will try it locally later, but do you really need to verify each mission in if statements? Why not use the value in the argument directly?

**Comment by tradej** [comment]
I don't see anything explicitly wrong with it, but the nginx [FAQ](http://nginx.org/en/docs/faq/variables_in_config.html) says variables are costly and should be avoided, so this is probably not what they had in mind.

**Comment by rhoads-zach** [comment]
i can update to remove the vars, but we have an inconsistency in naming. The following two missions uses LHS in the launcher and RHS in the docs:
* `rest-http` -> `http-api`
* `rest-http-secured` -> `secured`

I can modify this in the docs in this PR to make it consistent and skip setting the vars. @tradej @inoxx03 @Ladicek any objections?

**Comment by Ladicek** [comment]
No objection to changing the anchors.

**Comment by rhoads-zach** [comment]
@gastaldi @inoxx03 @tradej @Ladicek i changed the anchors, which allowed me to clean up the redirects.

We still have some attributes that use the old scheme, but they do not affect the anchors.  I'll clean those up in a follow up PR.

**Comment by inoxx03** [comment]
merging...

**Comment by inoxx03** [comment]
merged: 58418be72bb8b4a3326c10eba9adb74bf6aef300

**Pull request closed without merging**
