### PR TITLE
RHOARDOC-1590: Update Getting Started Guide to reflect Launcher changes

### PR DESCRIPTION
**Pull request by theashiot**
JIRA ID: RHOARDOC-1590
JIRA Link: https://issues.jboss.org/browse/RHOARDOC-1590

### CODE REVIEW

**Comment by theashiot** [comment]
A few notes about this PR:

- In the section "How the Fabric8 Launcher tool works" the wording includes tool because this is an existing module that is also included in the minishift guide. Should this module be updated or a new module created which uses the updated terminology?

- The definitions for runtimes in Red Hat OpenShift Application Runtimes need to be improved.

@tradej @inoxx03 take a look?

best,

ashwin

**Comment by theashiot** [comment]
> A few notes about this PR:
> 
> * In the section "How the Fabric8 Launcher tool works" the wording includes tool because this is an existing module that is also included in the minishift guide. Should this module be updated or a new module created which uses the updated terminology?
> * The definitions for runtimes in Red Hat OpenShift Application Runtimes need to be improved.
> 
> @tradej @inoxx03 take a look?
> 
> best,
> 
> ashwin

Also, as sugested in the doc analysis, "choosing capabilities of the applications" needs to be added "How Fabric8 launcher tool works"

**Comment by tradej** [comment]
ok to test

**Comment by tradej** [comment]
The content was approved by Thomas Qvarnstrom as an SME, merging.

**Pull request merged**
