### PR TITLE
RHOARDOC-1614-fix: File name and cleanup

### PR DESCRIPTION
**Pull request by huntley**
@tradej I need to do a final check of the links and cross references and will then remove the WIP

### CODE REVIEW

**Comment by tradej** [comment]
ok to test

**Comment by tradej** [comment]
@huntley, sure.

On a side note, there seem to be quite a lot of conflics, can you please rebase the branch, resolve the conflicts and then force push once you're done? It doesn't make much sense to review the PR before that is done. Thanks.

**Comment by huntley** [comment]
@tradej Added parameter for the examples catalog to document-attributes. Would you prefer document-attributes-launcher.

**Comment by tradej** [comment]
@huntley Thanks for resolving the conflicts and for creating the attribute.

@inoxx03, can you please review the PR?

**Pull request merged**
