### PR TITLE
DO NOT MERGE: RHOARDOC-1357 : Added assemblies to runtime guides

### PR DESCRIPTION
**Pull request by huntley**
Changes to document structure to more closely adhere to modular documentation concepts. New content to provide introductions to the new  assemblies.

### CODE REVIEW

**Comment by geoand** [comment]
@huntley Looks good! Just one question, where can I see the rendered preview of the changes?
Thanks

**Comment by geoand** [comment]
It's not really working for me at the moment - all I get is `Prepare to launch...`. But I trust it works :)

**Comment by geoand** [comment]
Oh, I see! Thanks @ncbaratta @huntley

**Comment by inoxx03** [comment]
This PR can not be completed due to low priority and lack of team resources. It will be closed and  can be reopened later.

**Pull request closed without merging**
