### PR TITLE
Removed duplicate anchor to resolve RHOARDOC 1364

### PR DESCRIPTION
**Pull request by huntley**

### CODE REVIEW

**Comment by rhoads-zach** [comment]
[test]

**Comment by rhoads-zach** [comment]
@tradej @inoxx03 can you two double check this? Technically its right, but i wanted to make sure there was no explicit reason for 2 anchors and i just missed it.

**Comment by tradej** [comment]
I'm fairly sure there wasn't a reason and it was just my script being too eager to insert anchors. My apologies.

**Comment by rhoads-zach** [comment]
np thank you @tradej

**Comment by rhoads-zach** [comment]
merging

**Pull request merged**
