### PR TITLE
Spring Boot Create App procedure removal rollback

### PR DESCRIPTION
**Pull request by tradej**
Notes:
* I have also reverted Vert.x changes because those can't be published yet. @liborfuka, please review.
* I have also removed the `check_launchpad` script because the file it references no longer exists and it blocks the CI verification.

HTML preview:

* SB 2.1 guide: https://url.corp.redhat.com/d81e4bb
* SB 1.5 guide: https://url.corp.redhat.com/db45f79

CC @huntley

### CODE REVIEW

**Comment by tradej** [comment]
retest this please

**Comment by gastaldi** [comment]
I think the `scripts/check_launchpad.sh` script can be removed too?

**Comment by tradej** [comment]
@gastaldi, thanks, of course, I forgot to `git rm` it.

**Comment by tradej** [comment]
Closing as a different decision was taken.

**Pull request closed without merging**
